CREATE TABLE STG_RETAIL_TRANSACTIONS (
    TRANSACTION_ID     VARCHAR2(50),
    TRANSACTION_DATE   VARCHAR2(50),
    CUSTOMER_ID        VARCHAR2(50),
    GENDER             VARCHAR2(10),
    AGE                NUMBER,
    PRODUCT_CATEGORY   VARCHAR2(100),
    QUANTITY           NUMBER,
    PRICE_PER_UNIT     NUMBER(10,2),
    TOTAL_AMOUNT       NUMBER(12,2)
);