SET LINESIZE 200
SET PAGESIZE 100
SET SERVEROUTPUT ON

PROMPT =============================
PROMPT ROW COUNTS
PROMPT =============================

SELECT 'STAGING' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM STG_RETAIL_TRANSACTIONS;
SELECT 'DIM_CUSTOMER', COUNT(*) FROM DIM_CUSTOMER;
SELECT 'DIM_PRODUCT', COUNT(*) FROM DIM_PRODUCT;
SELECT 'DIM_DATE', COUNT(*) FROM DIM_DATE;
SELECT 'FACT_SALES', COUNT(*) FROM FACT_SALES;

PROMPT =============================
PROMPT DISTINCT CHECKS
PROMPT =============================

SELECT 'DISTINCT_CUSTOMERS',
       COUNT(DISTINCT CUSTOMER_ID)
FROM STG_RETAIL_TRANSACTIONS;

SELECT 'DIM_CUSTOMER_ROWS',
       COUNT(*)
FROM DIM_CUSTOMER;

SELECT 'DISTINCT_PRODUCTS',
       COUNT(DISTINCT PRODUCT_CATEGORY)
FROM STG_RETAIL_TRANSACTIONS;

SELECT 'DIM_PRODUCT_ROWS',
       COUNT(*)
FROM DIM_PRODUCT;

PROMPT =============================
PROMPT REVENUE RECONCILIATION
PROMPT =============================

SELECT 'STAGING_TOTAL',
       SUM(TOTAL_AMOUNT)
FROM STG_RETAIL_TRANSACTIONS;

SELECT 'FACT_TOTAL',
       SUM(TOTAL_AMOUNT)
FROM FACT_SALES;

PROMPT =============================
PROMPT SAMPLE STAR JOIN
PROMPT =============================

SELECT
    d.FULL_DATE,
    c.CUSTOMER_ID,
    p.PRODUCT_CATEGORY,
    f.TOTAL_AMOUNT
FROM FACT_SALES f
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
JOIN DIM_CUSTOMER c ON f.CUSTOMER_KEY = c.CUSTOMER_KEY
JOIN DIM_PRODUCT p ON f.PRODUCT_KEY = p.PRODUCT_KEY
FETCH FIRST 5 ROWS ONLY;

PROMPT =============================
PROMPT FK NULL CHECK
PROMPT =============================

SELECT COUNT(*) AS NULL_FK_COUNT
FROM FACT_SALES
WHERE DATE_KEY IS NULL
   OR CUSTOMER_KEY IS NULL
   OR PRODUCT_KEY IS NULL;

PROMPT =============================
PROMPT VALIDATION COMPLETE
PROMPT =============================
