LOAD DATA
INFILE '/opt/retail/data/retail_sales_dataset.csv'
INTO TABLE STG_RETAIL_TRANSACTIONS
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  TRANSACTION_ID,
  TRANSACTION_DATE,
  CUSTOMER_ID,
  GENDER,
  AGE,
  PRODUCT_CATEGORY,
  QUANTITY,
  PRICE_PER_UNIT,
  TOTAL_AMOUNT
)